# -*- coding: utf-8 -*-
"""projeto1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SxrfUlFuNmtOlZHiR0oz0K1Nzr3WSi3e
"""

jogador1 = input('->Digite o nome do primeiro jogador: ')
jogador2 = input('->Digite o nome do segundo jogador: ')

print(f'//Quem será o primeiro a jogar?')
primeiro_jogador = input(f'-> Digite 1 para escolher {jogador1} ou 2 para escolher {jogador2}.')
segundo_jogador = None

if primeiro_jogador == '1':
  primeiro_jogador = jogador1
  segundo_jogador = jogador2
elif primeiro_jogador == '2':
  primeiro_jogador = jogador2
  segundo_jogador = jogador1

print(primeiro_jogador)

print(f'Agora escolha 1 para PAR ou 2 para ÍMPAR e dar ínicio ao jogo')

escolha = input(f'{primeiro_jogador} você quer PAR ou ÍMPAR?')
escolha2 = None

if escolha == 'ímpar' or escolha == 'impar' or escolha == '1':
  escolha = 'ímpar'
  escolha2 = 'par'
elif escolha == 'par' or escolha == '0':
  escolha = 'par'
  escolha2 = 'ímpar'
print(f'{primeiro_jogador} escolheu {escolha}')

numero1 = int(input(f' {primeiro_jogador} escolha um número: '))
numero2 = int(input(f' {segundo_jogador} escolha um número: '))
soma = numero1 + numero2
if soma % 2 == 0:
  vencedor = 'par'
else:
  vencedor = 'impar'
if vencedor == escolha:
  print(f'{primeiro_jogador} venceu.')
else:
  print(f'{segundo_jogador} venceu')